version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: mcp_chat_logger_rabbitmq
    ports:
      - "5672:5672"     # AMQP 포트
      - "15672:15672"   # 관리 웹 UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_init:/docker-entrypoint-initdb.d
    networks:
      - mcp_chat_logger_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  rabbitmq_data:
    driver: local

networks:
  mcp_chat_logger_network:
    driver: bridge
